name: Build Boost Android

on:
  workflow_dispatch:
    inputs:
      boost_version:
        description: "Boost version"
        required: true
        default: "1.90.0"
      ndk_version:
        description: "NDK version"
        required: true
        default: "26d"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOOST_VERSION: ${{ github.event.inputs.boost_version }}
      NDK_VERSION: ${{ github.event.inputs.ndk_version }}

    steps:
      - name: Checkout repo (tu fork)
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            curl \
            unzip

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r${NDK_VERSION}-linux.zip
          unzip android-ndk-r${NDK_VERSION}-linux.zip
          echo "NDK_ROOT=$PWD/android-ndk-r${NDK_VERSION}" >> $GITHUB_ENV

      - name: Make script executable
        run: chmod +x build-android.sh

      - name: Build Boost (only required libs)
        run: |
          ./build-android.sh \
            --boost=${BOOST_VERSION} \
            --with-libraries=chrono,thread,iostreams,date_time,filesystem,atomic,system \
            --arch=armeabi-v7a,arm64-v8a,x86_64,x86 \
            $NDK_ROOT

      - name: Verify built libraries
        run: |
          find build -name "libboost*.a"
      - name: Normalize and copy libs
        run: |
          ABIS="arm64-v8a armeabi-v7a x86 x86_64"

          for ABI in $ABIS; do
            mkdir -p output/libs/$ABI

            find build -path "*/$ABI/*" -name "libboost_*-clang-mt-*.a" -print0 | while IFS= read -r -d '' f; do
              base=$(basename "$f")

              simple=$(echo "$base" | sed -E 's/(libboost_[^ -]+).*/\1.a/')

              cp "$f" "output/libs/$ABI/$simple"
            done
          done
      - name: Copy headers
        run: |
          mkdir -p output/include

          HEADER_PATH=$(find build -type d -path "*/include/boost" | head -n 1)

          if [ -z "$HEADER_PATH" ]; then
            echo "ERROR: Boost headers not found"
            exit 1
          fi

          cp -r "$HEADER_PATH" output/include/
      - name: Package build
        run: |
          tar -czf boost-${BOOST_VERSION}-ndk-${NDK_VERSION}.tar.gz output
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: boost-${{ env.BOOST_VERSION }}-ndk-${{ env.NDK_VERSION }}
          name: Boost ${{ env.BOOST_VERSION }} (NDK ${{ env.NDK_VERSION }})
          draft: false
          prerelease: false
          files: boost-${{ env.BOOST_VERSION }}-ndk-${{ env.NDK_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}